#!/usr/bin/env python3
"""regenerate_vault.py

Scan the repository and regenerate Project-Map.md and per-folder index pages
inside the Obsidian vault. Optionally append a HANDOFF entry describing changes.

Usage:
  python regenerate_vault.py --repo-root ".." --vault "." --append-handoff \
    --agent "agent-name" --action updated --summary "Updated indexes" --files file1 file2

This script is intentionally simple and safe: it writes markdown files inside the
vault folder and appends to HANDOFF.MD if requested.
"""
import argparse
import os
from pathlib import Path
import datetime


def scan_top_level(repo_root: Path, vault: Path):
    entries = []
    for p in sorted(repo_root.iterdir()):
        if p.resolve() == vault.resolve():
            # skip the vault itself if repo_root points to parent
            continue
        if p.name.startswith('.') or p.name.endswith('.egg-info'):
            continue
        if p.name in {'build', 'dist', '__pycache__', '.pytest_cache'}:
            continue
        entries.append(p.name + ('/' if p.is_dir() else ''))
    return entries


def write_project_map(vault: Path, entries):
    out = vault / 'Project-Map.md'
    lines = [
        '# Project Map — stochpylib\n',
        '\n',
        'This file is generated by `regenerate_vault.py`. It lists top-level files and folders.\n',
        '\n',
    ]
    for e in entries:
        target = Path('..') / e
        lines.append(f'- [{e}]({target.as_posix()})\n')
    lines.append('\n')
    out.write_text(''.join(lines), encoding='utf-8')
    print('Wrote', out)


def write_folder_indexes(vault: Path, repo_root: Path):
    out_dir = vault / 'code' / 'folders'
    out_dir.mkdir(parents=True, exist_ok=True)
    
    def write_index_recursive(folder_path, repo_root_path, indent=0, max_depth=None):
        lines = []
        for child in sorted(folder_path.iterdir()):
            if child.name.startswith('.'):
                continue
            rel = Path('..') / '..' / '..' / child.relative_to(repo_root_path)
            prefix = '  ' * indent
            if child.is_dir():
                lines.append(f'{prefix}- **{child.name}/**\n')
                if max_depth is None or indent + 1 < max_depth:
                    lines.extend(write_index_recursive(child, repo_root_path, indent + 1, max_depth))
            else:
                lines.append(f'{prefix}- [{child.name}]({rel.as_posix()})\n')
        return lines

    skip_dirs = {'build', 'dist', '__pycache__', '.pytest_cache'}
    for d in sorted(p for p in repo_root.iterdir() if p.is_dir() and not p.name.startswith('.')):
        if d.resolve() == vault.resolve() or d.name in skip_dirs or d.name.endswith('.egg-info'):
            continue
        idx = out_dir / (d.name + '.md')
        lines = [f'# {d.name}\n\n', f'Contents of `{d.name}/`:\n\n']
        # Show immediate files and top-level subfolder names only (one-level deep)
        lines.extend(write_index_recursive(d, repo_root, indent=0, max_depth=1))
        idx.write_text(''.join(lines), encoding='utf-8')
        print('Wrote', idx)


def append_handoff(vault: Path, agent: str, action: str, summary: str, files: list):
    handoff = vault / 'HANDOFF.MD'
    ts = datetime.datetime.utcnow().replace(microsecond=0).isoformat() + 'Z'
    lines = [
        '\n',
        f'- **Timestamp:** {ts}\n',
        f'- **Agent:** {agent}\n',
        f'- **Action:** {action}\n',
        f'- **Summary:** {summary}\n',
        f'- **Files changed:** {", ".join(files) if files else "none"}\n',
        '\n'
    ]
    handoff.write_text(handoff.read_text(encoding='utf-8') + '\n'.join(lines), encoding='utf-8')
    print('Appended HANDOFF entry')


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--repo-root', default='..')
    p.add_argument('--vault', default='.')
    p.add_argument('--append-handoff', action='store_true')
    p.add_argument('--agent', default='agent')
    p.add_argument('--action', default='updated')
    p.add_argument('--summary', default='Regenerated vault indexes')
    p.add_argument('--files', nargs='*', default=[])
    args = p.parse_args()

    repo_root = Path(args.repo_root).resolve()
    vault = Path(args.vault).resolve()

    entries = scan_top_level(repo_root, vault)
    write_project_map(vault, entries)
    write_folder_indexes(vault, repo_root)

    if args.append_handoff:
        append_handoff(vault, args.agent, args.action, args.summary, args.files)


if __name__ == '__main__':
    main()
